source 'https://rubygems.org'

gem 'jekyll', github: 'jekyll/jekyll'
gem 'rouge'
# gem 'redcarpet',  '>=3.0.0'
# gem 'RedCloth',   '=4.2.9'

# gem 'haml'
# gem 'github-pages'
# gem "redcarpet", github: "triplecanopy/redcarpet"
